all: main.cpp helper.cpp memory.cpp instruction.cpp process.cpp process_table.cpp
	g++ -o Simulate main.cpp helper.cpp memory.cpp instruction.cpp process.cpp process_table.cpp
clean: 
	$(RM) Simulate
